const fs = require('fs');
const path = require('path');

// =========================================================================
// 1. FLASHCARDS MOCK COMPLETAS CON NUEVA ARQUITECTURA (TRADUCCIONES FLEXIBLES & FONÉTICA DUAL)
// =========================================================================
const INITIAL_FLASHCARDS = [
  {
    id: 'fc-obj-1',
    targetWord: 'Coffee Mug',
    primaryTranslation: 'Taza',
    acceptedTranslations: ['taza', 'pocillo', 'mug', 'taza de café', 'taza de cafe'],
    minInputLength: 4,
    displayTranslation: 'Taza de Café (Mug)',
    nativeTranslation: 'Taza de Café',
    cardType: 'VOCABULARY',
    partOfSpeech: 'NOUN',
    conceptCategory: 'OBJECT',
    facilitatedPhonetics: 'kófi mag',
    phoneticScript: '/ˈkɒf.i mʌɡ/',
    contextSentence: 'She poured hot Colombian coffee into her ceramic mug.',
    contextTranslation: 'Ella sirvió café colombiano caliente en su taza de cerámica.',
    mnemonicHint: 'Imagina una taza humeante en tu escritorio de trabajo.',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd',
    imageSource: 'CAMERA',
    createdVia: 'CAMERA',
    createdAt: '2026-09-01T23:07:16.831Z',
    repetitionNumber: 1,
    easeFactor: 2.5,
    intervalDays: 1,
    lastRating: 'GOOD',
    nextReviewAt: '2026-09-02T23:07:16.832Z',
  },
  {
    id: 'fc-obj-2',
    targetWord: 'Laptop',
    primaryTranslation: 'Portátil',
    acceptedTranslations: ['portátil', 'portatil', 'computador', 'laptop', 'computadora', 'computador portátil'],
    minInputLength: 6,
    displayTranslation: 'Portátil / Computadora',
    nativeTranslation: 'Computadora Portátil',
    cardType: 'VOCABULARY',
    partOfSpeech: 'NOUN',
    conceptCategory: 'OBJECT',
    facilitatedPhonetics: 'láptop',
    phoneticScript: '/ˈlæp.tɒp/',
    contextSentence: 'Open your laptop to start coding the mobile application.',
    contextTranslation: 'Abre tu portátil para empezar a programar la aplicación móvil.',
    mnemonicHint: 'Lap (regazo) + Top (encima): la máquina que pones sobre tu regazo.',
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853',
    imageSource: 'CAMERA',
    createdVia: 'CAMERA',
    createdAt: '2026-09-01T23:07:16.832Z',
    repetitionNumber: 0,
    easeFactor: 2.5,
    intervalDays: 0,
    nextReviewAt: '2026-09-01T23:07:16.832Z',
  },
  {
    id: 'fc-obj-3',
    targetWord: 'Backpack',
    primaryTranslation: 'Mochila',
    acceptedTranslations: ['mochila', 'morral', 'bolso', 'bulto'],
    minInputLength: 5,
    displayTranslation: 'Mochila / Morral',
    nativeTranslation: 'Mochila / Morral',
    cardType: 'VOCABULARY',
    partOfSpeech: 'NOUN',
    conceptCategory: 'OBJECT',
    facilitatedPhonetics: 'bákpak',
    phoneticScript: '/ˈbæk.pæk/',
    contextSentence: 'He packed his laptop and notebook inside his sturdy backpack.',
    contextTranslation: 'Empacó su portátil y cuaderno dentro de su mochila resistente.',
    mnemonicHint: 'Back (espalda) + Pack (paquete): el paquete que llevas en la espalda.',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62',
    imageSource: 'CAMERA',
    createdVia: 'CAMERA',
    createdAt: '2026-09-01T23:07:16.832Z',
    repetitionNumber: 0,
    easeFactor: 2.5,
    intervalDays: 0,
    nextReviewAt: '2026-09-01T23:07:16.832Z',
  },
  {
    id: 'fc-idiom-1',
    targetWord: 'Break the ice',
    primaryTranslation: 'Romper el hielo',
    acceptedTranslations: ['romper el hielo', 'romper el silencio', 'iniciar conversación', 'iniciar conversacion'],
    minInputLength: 15,
    displayTranslation: 'Romper el hielo',
    nativeTranslation: 'Romper el hielo',
    cardType: 'IDIOM',
    partOfSpeech: 'PHRASE',
    conceptCategory: 'IDIOM',
    facilitatedPhonetics: 'bréik di áis',
    phoneticScript: '/breɪk ðiː aɪs/',
    contextSentence: 'Telling a friendly joke is a great way to break the ice in Colombia.',
    contextTranslation: 'Contar un chiste amistoso es una excelente forma de romper el hielo en Colombia.',
    mnemonicHint: 'Imagina romper un témpano frío para que fluya la conversación.',
    imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9',
    imageSource: 'PRESET',
    createdVia: 'SEARCH',
    createdAt: '2026-09-01T23:07:16.832Z',
    repetitionNumber: 0,
    easeFactor: 2.5,
    intervalDays: 0,
    nextReviewAt: '2026-09-01T23:07:16.832Z',
  },
  {
    id: 'fc-con-1',
    targetWord: 'Although',
    primaryTranslation: 'Aunque',
    acceptedTranslations: ['aunque', 'a pesar de que', 'si bien'],
    minInputLength: 6,
    displayTranslation: 'Aunque / A pesar de que',
    nativeTranslation: 'Aunque / A pesar de que',
    cardType: 'CONNECTOR',
    partOfSpeech: 'CONJUNCTION',
    conceptCategory: 'CONNECTOR',
    facilitatedPhonetics: 'ol-dóu',
    phoneticScript: '/ɔːlˈðoʊ/',
    contextSentence: 'Although it rained heavily in Bogota, we went to the university.',
    contextTranslation: 'Aunque llovió fuertemente en Bogotá, fuimos a la universidad.',
    mnemonicHint: 'Al-though: todo a través de la dificultad (a pesar de).',
    imageUrl: 'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17',
    imageSource: 'PRESET',
    createdVia: 'SEARCH',
    createdAt: '2026-09-01T23:07:16.832Z',
    repetitionNumber: 0,
    easeFactor: 2.5,
    intervalDays: 0,
    nextReviewAt: '2026-09-01T23:07:16.832Z',
  },
  {
    id: 'fc-adj-1',
    targetWord: 'Exhausted',
    primaryTranslation: 'Agotado',
    acceptedTranslations: ['agotado', 'exhausto', 'muy cansado', 'cansado'],
    minInputLength: 7,
    displayTranslation: 'Agotado / Exhausto',
    nativeTranslation: 'Agotado / Exhausto',
    cardType: 'VOCABULARY',
    partOfSpeech: 'ADJECTIVE',
    conceptCategory: 'ABSTRACT_CONCEPT',
    facilitatedPhonetics: 'ig-zós-tid',
    phoneticScript: '/ɪɡˈzɔː.stɪd/',
    contextSentence: 'After studying English for five hours, I was completely exhausted.',
    contextTranslation: 'Después de estudiar inglés durante cinco horas, estaba completamente agotado.',
    mnemonicHint: 'Como el tubo de escape de un auto: sin energía.',
    imageUrl: 'https://images.unsplash.com/photo-1541199249251-f713e6145474',
    imageSource: 'PRESET',
    createdVia: 'SEARCH',
    createdAt: '2026-09-01T23:07:16.832Z',
    repetitionNumber: 0,
    easeFactor: 2.5,
    intervalDays: 0,
    nextReviewAt: '2026-09-01T23:07:16.832Z',
  },
  {
    id: 'fc-phrasal-1',
    targetWord: 'Give up',
    primaryTranslation: 'Rendirse',
    acceptedTranslations: ['rendirse', 'abandonar', 'darse por vencido'],
    minInputLength: 8,
    displayTranslation: 'Rendirse / Darse por vencido',
    nativeTranslation: 'Rendirse / Darse por vencido',
    cardType: 'PHRASAL_VERB',
    partOfSpeech: 'VERB',
    conceptCategory: 'PHRASAL_VERB',
    facilitatedPhonetics: 'giv áp',
    phoneticScript: '/ɡɪv ʌp/',
    contextSentence: 'Never give up when learning English grammar rules.',
    contextTranslation: 'Nunca te rindas al aprender las reglas gramaticales del inglés.',
    mnemonicHint: 'Dar hacia arriba tus brazos en señal de entrega.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5',
    imageSource: 'PRESET',
    createdVia: 'SEARCH',
    createdAt: '2026-09-01T23:07:16.832Z',
    repetitionNumber: 0,
    easeFactor: 2.5,
    intervalDays: 0,
    nextReviewAt: '2026-09-01T23:07:16.832Z',
  },
  {
    id: 'fc-adv-1',
    targetWord: 'Actually',
    primaryTranslation: 'En realidad',
    acceptedTranslations: ['en realidad', 'de hecho', 'realmente'],
    minInputLength: 9,
    displayTranslation: 'En realidad / De hecho',
    nativeTranslation: 'En realidad / De hecho',
    cardType: 'FALSE_FRIEND',
    partOfSpeech: 'ADVERB',
    conceptCategory: 'FALSE_FRIEND',
    facilitatedPhonetics: 'ák-chu-a-li',
    phoneticScript: '/ˈæk.tʃu.ə.li/',
    contextSentence: 'Actually, I have never been to London before.',
    contextTranslation: 'En realidad, nunca he estado en Londres antes.',
    mnemonicHint: 'Falso amigo: no significa actualmente, sino de hecho/en verdad.',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8',
    imageSource: 'PRESET',
    createdVia: 'SEARCH',
    createdAt: '2026-09-01T23:07:16.832Z',
    repetitionNumber: 0,
    easeFactor: 2.5,
    intervalDays: 0,
    nextReviewAt: '2026-09-01T23:07:16.832Z',
  },
  {
    id: 'fc-hab-1',
    targetWord: 'Used to',
    primaryTranslation: 'Solía',
    acceptedTranslations: ['solía', 'solia', 'acostumbraba', 'antes hacía', 'antes hacia'],
    minInputLength: 5,
    displayTranslation: 'Solía (hábito pasado)',
    nativeTranslation: 'Solía (hábito pasado)',
    cardType: 'GRAMMAR_RULE',
    partOfSpeech: 'VERB',
    conceptCategory: 'GRAMMAR_RULE',
    facilitatedPhonetics: 'iúzd tu',
    phoneticScript: '/ˈjuːzd tuː/',
    contextSentence: 'I used to live in Cali before moving to Bogota.',
    contextTranslation: 'Solía vivir en Cali antes de mudarme a Bogotá.',
    mnemonicHint: 'Cosas que usabas hacer en el pasado regularmente.',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211',
    imageSource: 'PRESET',
    createdVia: 'SEARCH',
    createdAt: '2026-09-01T23:07:16.832Z',
    repetitionNumber: 0,
    easeFactor: 2.5,
    intervalDays: 0,
    nextReviewAt: '2026-09-01T23:07:16.832Z',
  }
];

// =========================================================================
// 2. DICCIONARIO DE DISPARADORES EN ESPAÑOL
// =========================================================================
const VOICE_CONCEPT_DICTIONARY = [
  {
    spanishTrigger: 'romper el hielo',
    targetWord: 'Break the ice',
    nativeTranslation: 'Romper el hielo',
    category: 'IDIOM',
    partOfSpeech: 'PHRASE',
    phoneticScript: '/breɪk ðiː aɪs/',
    contextSentence: 'Telling a friendly joke is a great way to break the ice in Colombia.',
    contextTranslation: 'Contar un chiste amistoso es una excelente forma de romper el hielo en Colombia.',
    mnemonicHint: 'Imagina romper un témpano frío para que fluya la conversación.',
    imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9',
  },
  {
    spanishTrigger: 'arrepentirse',
    targetWord: 'Regret',
    nativeTranslation: 'Arrepentirse / Lamentar',
    category: 'ABSTRACT_CONCEPT',
    partOfSpeech: 'VERB',
    phoneticScript: '/rɪˈɡret/',
    contextSentence: 'I never regret dedicating an hour a day to my English practice.',
    contextTranslation: 'Nunca me arrepiento de dedicar una hora al día a mi práctica de inglés.',
    mnemonicHint: 'Re-gret: regresar mentalmente a un error lamentándolo.',
    imageUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843',
  },
  {
    spanishTrigger: 'agotado',
    targetWord: 'Exhausted',
    nativeTranslation: 'Agotado / Exhausto',
    category: 'ABSTRACT_CONCEPT',
    partOfSpeech: 'ADJECTIVE',
    phoneticScript: '/ɪɡˈzɔː.stɪd/',
    contextSentence: 'After studying English for five hours, I was completely exhausted.',
    contextTranslation: 'Después de estudiar inglés durante cinco horas, estaba completamente agotado.',
    mnemonicHint: 'Como el tubo de escape de un auto: sin energía.',
    imageUrl: 'https://images.unsplash.com/photo-1541199249251-f713e6145474',
  },
  {
    spanishTrigger: 'rendirse',
    targetWord: 'Give up',
    nativeTranslation: 'Rendirse / Darse por vencido',
    category: 'PHRASAL_VERB',
    partOfSpeech: 'VERB',
    phoneticScript: '/ɡɪv ʌp/',
    contextSentence: 'Never give up when learning English grammar rules.',
    contextTranslation: 'Nunca te rindas al aprender las reglas gramaticales del inglés.',
    mnemonicHint: 'Dar hacia arriba tus brazos en señal de entrega.',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5',
  },
  {
    spanishTrigger: 'en realidad',
    targetWord: 'Actually',
    nativeTranslation: 'En realidad / De hecho',
    category: 'FALSE_FRIEND',
    partOfSpeech: 'ADVERB',
    phoneticScript: '/ˈæk.tʃu.ə.li/',
    contextSentence: 'Actually, I have never been to London before.',
    contextTranslation: 'En realidad, nunca he estado en Londres antes.',
    mnemonicHint: 'No es actualmente; es un hecho actual real.',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8',
  },
  {
    spanishTrigger: 'solía',
    targetWord: 'Used to',
    nativeTranslation: 'Solía (hábito pasado)',
    category: 'GRAMMAR_RULE',
    partOfSpeech: 'VERB',
    phoneticScript: '/ˈjuːzd tuː/',
    contextSentence: 'I used to live in Cali before moving to Bogota.',
    contextTranslation: 'Solía vivir en Cali antes de mudarme a Bogotá.',
    mnemonicHint: 'Cosas que usabas hacer en el pasado.',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211',
  }
];

// =========================================================================
// 3. MAPA DE PRERREQUISITOS ESTRICTOS (DAG 20 NODOS BALANCEADOS)
// =========================================================================
const PREREQUISITES_MAP_20 = {
  'a1_node_1': [],
  'a1_node_2': ['a1_node_1'],
  'a1_node_3': ['a1_node_1'],
  'a1_node_4': ['a1_node_2'],
  'a1_node_5': ['a1_node_3'],
  'a1_node_6': ['a1_node_4'],
  'a1_node_7': ['a1_node_5'],
  'a1_node_8': ['a1_node_6', 'a1_node_7'],
  'a1_node_9': ['a1_node_8'],
  'a1_node_10': ['a1_node_9'],
  'a2_node_11': ['a1_node_10'],
  'a2_node_12': ['a2_node_11'],
  'a2_node_13': ['a1_node_10'],
  'a2_node_14': ['a2_node_13'],
  'a2_node_15': ['a2_node_14'],
  'a2_node_16': ['a1_node_10'],
  'a2_node_17': ['a2_node_16'],
  'a2_node_18': ['a2_node_17'],
  'a2_node_19': ['a2_node_12', 'a2_node_15', 'a2_node_18'],
  'a2_node_20': ['a2_node_19']
};

console.log("Building 20-node master curriculum...");
